In [188]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [189]:
data = pd.read_csv(r"C:\Users\ekta panchbhai\OneDrive\Desktop\Python 6326\sales 1.csv")
data.head(1)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,column_1,column_2,Region_Id
0,0,2/19/2016,2016,February,29,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.0,109.0,80,109.0,NaN,NaN,101

In [190]:
data.shape

(34883, 18)

# drop column

In [191]:
data.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Making Cost', 'Revenue', 'column_1',
       'column_2', 'Region_Id'],
      dtype='object')

In [192]:
data.drop(columns=['index','column_1','column_2'], inplace= True)

# fill null value

In [193]:
data.shape[0] * 0.05

1744.15

In [194]:
data.isnull().sum().values.sum()

np.int64(228)

In [195]:
data.isnull().sum()

Date                 14
Year                  0
Month                11
Customer Age          0
Customer Gender       3
Country              28
State                10
Product Category      2
Sub Category          0
Quantity              1
Unit Cost             4
Unit Price            4
Making Cost           0
Revenue             151
Region_Id             0
dtype: int64

In [196]:
data.dtypes

Date                 object
Year                  int64
Month                object
Customer Age          int64
Customer Gender      object
Country              object
State                object
Product Category     object
Sub Category         object
Quantity            float64
Unit Cost           float64
Unit Price          float64
Making Cost           int64
Revenue             float64
Region_Id             int64
dtype: object

In [197]:
x  = data["Date"].mode()[0]
x

'03-01-2016'

In [198]:
data["Date"].fillna(value= x, inplace= True)

In [199]:
data.columns

Index(['Date', 'Year', 'Month', 'Customer Age', 'Customer Gender', 'Country',
       'State', 'Product Category', 'Sub Category', 'Quantity', 'Unit Cost',
       'Unit Price', 'Making Cost', 'Revenue', 'Region_Id'],
      dtype='object')

In [200]:
data.Revenue.mean()

np.float64(640.7721985488886)

In [201]:
data.Revenue.median()

317.0

In [202]:
def fill_null_valuese(data_frame_name):
    
    for column in data_frame_name.columns:
        
        if data_frame_name[column].isnull().sum() > 0:
            
            if data_frame_name[column].dtypes in ['int64', 'int32', 'float64', 'float32' ]:
                data_frame_name[column].fillna(value = data_frame_name[column].mean(), inplace = True )
                
            else :
                data_frame_name[column].fillna(value = data_frame_name[column].mode()[0], inplace = True )
                
    return print( f"Fill Null values  operaction has been Done \n{data_frame_name.isnull().sum()}")

In [203]:
fill_null_valuese(data)

Fill Null values  operaction has been Done
Date                0
Year                0
Month               0
Customer Age        0
Customer Gender     0
Country             0
State               0
Product Category    0
Sub Category        0
Quantity            0
Unit Cost           0
Unit Price          0
Making Cost         0
Revenue             0
Region_Id           0
dtype: int64

# Dropduplicated

In [204]:
data.duplicated().sum()

np.int64(4)

In [205]:
data[ data.duplicated() ]

,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,Region_Id
34869,03-12-2016,2016,March,29,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.5,116.500000,175,233.0,102
34870,03-12-2016,2016,March,29,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.0,41.666667,105,125.0,102
34872,4/17/2016,2016,April,29,F,United States,Washington,Accessories,Tires and Tubes,2.0,52.0,60.000000,104,120.0,104
34878,7/22/2016,2016,July,29,F,United States,Washington,Accessories,Tires and Tubes,2.0,46.0,60.000000,92,120.0,102

In [206]:
# row -- drop_duplicates, drona, remove rows
data = data.drop_duplicates().reset_index(drop= True)

# change data type of column

In [207]:
data["Quantity"] = data["Quantity"].astype('int64')

In [208]:
pd.to_datetime(data["Date"], errors='coerce')

0       2016-02-19
1       2016-02-20
2       2016-02-27
3              NaT
4              NaT
           ...
34874          NaT
34875   2016-07-22
34876   2015-08-18
34877   2015-08-30
34878   2015-09-17
Name: Date, Length: 34879, dtype: datetime64[ns]

In [209]:
# change data type of column
data['Date'] = data['Date'].astype('datetime64[ns]')

# add Column

In [210]:
data.drop(columns = ['Year',	'Month'], inplace=True)

# add Column Date column

In [211]:
# add Column

data["Month_name"] = data['Date'].dt.month_name()

In [212]:

data["Year"] = data['Date'].dt.year

In [213]:
data["Day_names"] = data["Date"].dt.day_name()

In [214]:
data["Quater"] = data["Date"].dt.quarter

# add column Profit

In [215]:
data["Profit"] = data["Revenue"] - data["Making Cost"]

In [216]:
np.where(data["Profit"]> 0, 'Profit', 'Loss')

array(['Profit', 'Profit', 'Profit', ..., 'Profit', 'Profit', 'Profit'],
      dtype='<U6')

In [217]:
data["Profit_loss_Status"] = np.where(data["Profit"]> 0, 'Profit', 'Loss')
data

,Date,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Making Cost,Revenue,Region_Id,Month_name,Year,Day_names,Quater,Profit,Profit_loss_Status
0,2016-02-19,29,F,United States,Washington,Accessories,Tires and Tubes,1,80.00,109.000000,80,109.0,101,February,2016,Friday,1,29.0,Profit
1,2016-02-20,29,F,United States,Washington,Clothing,Gloves,2,24.50,28.500000,49,57.0,103,February,2016,Saturday,1,8.0,Profit
2,2016-02-27,29,F,United States,Washington,Accessories,Tires and Tubes,3,3.67,5.000000,11,15.0,102,February,2016,Saturday,1,4.0,Profit
3,2016-03-12,29,F,United States,Washington,Accessories,Tires and Tubes,2,87.50,116.500000,175,233.0,102,March,2016,Saturday,1,58.0,Profit
4,2016-03-12,29,F,United States,Washington,Accessories,Tires and Tubes,3,35.00,41.666667,105,125.0,102,March,2016,Saturday,1,20.0,Profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34874,2016-07-01,29,F,United States,Washington,Accessories,Tires and Tubes,3,40.00,48.666667,120,146.0,103,July,2016,Friday,3,26.0,Profit
34875,2016-07-22,29,F,United States,Washington,Accessories,Tires and Tubes,1,9.00,10.000000,9,10.0,101,July,2016,Friday,3,1.0,Profit
34876,2015-08-18,29,F,United States,Washington,Accessories,Helmets,3,151.67,181.333333,455,544.0,102,August,2015,Tuesday,3,89.0,Profit
34877,2015-08-30,29,F,United States,Washington,Accessories,Tires and Tubes,3,70.00,72.666667,210,218.0,103,August,2015,Sunday,3,8.0,Profit
34878,2015-09-17,29,F,United States,Washington,Accessories,Tires and Tubes,1,385.00,439.000000,385,439.0,103,September,2015,Thursday,3,54.0,Profit

In [218]:
data["Customer Gender"].value_counts()

Customer Gender
M    17806
F    17073
Name: count, dtype: int64

In [219]:
data["Customer Gender"].unique()

array(['F', 'M'], dtype=object)

In [220]:
data["Customer Gender"].count()

np.int64(34879)

In [221]:
data.columns

Index(['Date', 'Customer Age', 'Customer Gender', 'Country', 'State',
       'Product Category', 'Sub Category', 'Quantity', 'Unit Cost',
       'Unit Price', 'Making Cost', 'Revenue', 'Region_Id', 'Month_name',
       'Year', 'Day_names', 'Quater', 'Profit', 'Profit_loss_Status'],
      dtype='object')

In [222]:

columnss = ['Customer Gender', 'Country', 
       'Product Category', 'Sub Category', 'Quantity', 
       'Month_name','Year', 'Day_names', 'Quater',  
       'Profit_loss_Status']

for column in columnss:
    print(data[column].value_counts())
    print("\n---------------------------")

Customer Gender
M    17806
F    17073
Name: count, dtype: int64

---------------------------
Country
United States     18089
United Kingdom     6421
Germany            5201
France             5168
Name: count, dtype: int64

---------------------------
Product Category
Accessories    22546
Bikes           7093
Clothing        5240
Name: count, dtype: int64

---------------------------
Sub Category
Tires and Tubes      11122
Bottles and Cages     5295
Helmets               4178
Road Bikes            3022
Mountain Bikes        2737
Jerseys               2000
Caps                  1517
Touring Bikes         1334
Fenders                762
Shorts                 566
Cleaners               545
Gloves                 481
Hydration Packs        396
Socks                  364
Vests                  312
Bike Stands            145
Bike Racks             103
Name: count, dtype: int64

---------------------------
Quantity
2    11772
3    11597
1    11510
Name: count, dtype: int64

---------------------------
Month_name
June         3683
May          3676
December     3412
April        3281
March        3167
January      2904
February     2889
October      2553
November     2487
August       2306
September    2304
July         2217
Name: count, dtype: int64

---------------------------
Year
2016    19861
2015    15018
Name: count, dtype: int64

---------------------------
Day_names
Friday       5138
Sunday       5078
Tuesday      5075
Saturday     5036
Wednesday    4920
Thursday     4838
Monday       4794
Name: count, dtype: int64

---------------------------
Quater
2    10640
1     8960
4     8452
3     6827
Name: count, dtype: int64

---------------------------
Profit_loss_Status
Profit    29580
Loss       5299
Name: count, dtype: int64

---------------------------